[app]

# (str) Titre de ton application
title = Mon Catalogue Tunisie

# (str) Nom du paquet (sans espaces ni majuscules)
package.name = cataloguetunisie

# (str) Domaine
package.domain = org.tunisie

# (str) Source code (le dossier où se trouve main.py)
source.dir = .

# (list) Extensions de fichiers à inclure
source.include_exts = py,png,jpg,kv,atlas

# (str) Version de l'application
version = 0.1

# (list) Bibliothèques nécessaires (TRÈS IMPORTANT)
requirements = python3,kivy,requests,urllib3,certifi,charset-normalizer,idna

# (str) Orientation (paysage ou portrait)
orientation = portrait

# (bool) Plein écran
fullscreen = 0

# (list) Permissions Android
android.permissions = INTERNET, WRITE_EXTERNAL_STORAGE, READ_EXTERNAL_STORAGE

# (list) Architectures supportées (pour les téléphones récents)
android.archs = arm64-v8a, armeabi-v7a

# (bool) Autoriser la sauvegarde
android.allow_backup = True

# (int) Niveau de l'API Android (33 est le standard actuel)
android.api = 33

# (str) Format de sortie (ne pas changer)
android.release_artifact = apk
